export default {
    MAKE_NOTIFICATION_AS_READ_BY_ID: "MAKE_NOTIFICATION_AS_READ_BY_ID",
    MAKE_ALL_NOTIFICATION_AS_READ: "MAKE_ALL_NOTIFICATION_AS_READ",
    GET_ALL_NOTIFICATIONS_LIST: "GET_ALL_NOTIFICATIONS_LIST",
    START_REQUEST: "START_REQUEST",
    FINISH_REQUEST: "FINISH_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED"
}